logo:
  subtitle: 开放互助 活跃创新|做优质的自发性技术协助组织

menubar:
  columns: 4
  items:
    - id: nav
      title: 导航
      url: /
    - id: post
      title: 博客
      url: /blog/
    - id: link
      title: 合作
      url: /link/
    - id: about
      title: 关于
      url: /about/

footer:
  content: |
    © 2020-2024 <span class="font-sht">野生技协</span>(TECHYES). All rights reserved.
    如果你想部署网站/提交链接/对本页面提出建议，请联系QQ: 2399052066(纸鹿)。
    <i class="fa-brands fa-qq"></i>[QQ群: 89 4656 456](https://jq.qq.com/?_wv=1027&k=CRVRq4sD)　<i class="fa-brands fa-telegram"></i>[TG群: YesTech](https://t.me/yestech)　<i class="fa-brands fa-github"></i>[L33Z22L11/TechyesNav](https://github.com/L33Z22L11/TechyesNav)
    <i class='fa-solid fa-palette'></i>[Stellar](https://github.com/xaoxuu/hexo-theme-stellar)　<i class='fa-brands fa-creative-commons'></i>[BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)

inject:
  head:
    - <link rel="stylesheet" href="//s1.hdslb.com/bfs/static/jinkela/long/font/regular.css" media="none" onload="this.media='all'">
    - <link rel="stylesheet" href="//s1.hdslb.com/bfs/static/jinkela/long/font/medium.css" media="none" onload="this.media='all'">
    - <link rel="stylesheet" href="https://lib.baomitu.com/font-awesome/6.5.1/css/all.min.css" media="none" onload="this.media='all'">
    - <link rel="stylesheet" href="/css/font.css">

style:
  font-family:
    logo: AlimamaShuHeiTi
    body: HarmonyOS_Regular
  sidebar:
    background: "linear-gradient(60deg, #acd, #ced)"
